[project]
name = "mlperf-inference-multimodal-vl2l"
description = "The reference implementation for the vision-language-to-language (VL2L) benchmark in MLPerf Inference"
readme = "README.md"
classifiers = [
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Intended Audience :: Developers",
  "Operating System :: POSIX :: Linux",
]
requires-python = ">=3.13"
dependencies = [
  "datasets",
  "loguru",
  "matplotlib",
  "mlcommons_loadgen",
  "openai[aiohttp]",
  "pydantic",
  "pydantic-typer",
  "typer",
]
dynamic = ["version"]

[project.optional-dependencies]
dev = ["black", "ruff", "mypy", "shellcheck-py", "pytest"]

[project.scripts]
mlperf-inf-mm-vl2l = "mlperf_inference_multimodal_vl2l.cli:app"

[project.urls]
Homepage = "https://github.com/mlcommons/inference/multimodal/vl2l"

[build-system]
requires = ["setuptools>=80", "setuptools-scm[simple]>=8"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"mlperf_inference_multimodal_vl2l" = ["py.typed"]

[tool.setuptools_scm]
root = "../../"

[tool.ruff]
lint.select = ["ALL"]
lint.ignore = [
  "ANN002",  # Missing type annotation for `*args`"
  "ANN003",  # Missing type annotation for `**kwargs`
]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.mypy]
check_untyped_defs = true
plugins = ['pydantic.mypy']

[[tool.mypy.overrides]]
module = "pydantic_typer"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "mlperf_loadgen"
ignore_missing_imports = true
